name: Scheduled Main Job

on:
  schedule:
    - cron: "0 * * * *" # Runs hourly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Prisma client
        run: python3 -m prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run main script
        run: python main.py
        env:
          CLOUDINARY_COVER_CLOUD_NAME: ${{ secrets.CLOUDINARY_COVER_CLOUD_NAME }}
          CLOUDINARY_COVER_API_KEY: ${{ secrets.CLOUDINARY_COVER_API_KEY }}
          CLOUDINARY_COVER_API_SECRET: ${{ secrets.CLOUDINARY_COVER_API_SECRET }}
          CLOUDINARY_CONTENT_CLOUD_NAME: ${{ secrets.CLOUDINARY_CONTENT_CLOUD_NAME }}
          CLOUDINARY_CONTENT_API_KEY: ${{ secrets.CLOUDINARY_CONTENT_API_KEY }}
          CLOUDINARY_CONTENT_API_SECRET: ${{ secrets.CLOUDINARY_CONTENT_API_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update data from cron job" || echo "No changes to commit"
          if [ -n "$(git status --porcelain)" ]; then
            git pull --rebase origin main
            git push
          else
            echo "No changes to push"
          fi
